### ISSUE TITLE
IOS don't get notification when application is killed

### ISSUE THREAD

**Issue by oleksiiSevrukovRedvike** [twilio/twilio-voice-react-native#434] opened 2024-10-09 21:13 UTC
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
I don't get call notification when application is killed. I used await voice.initializePushRegistry() and export const voice = Object.freeze(new Voice())

## Expected Behavior
Notification should appear when application is killed and tap on it should launch application

## Actual Behavior
Notification has not appeared when application is killed

## Reproduction Frequency
It appears every time

## Software and Device Information
**Please complete the following information.**
 - Device: [iPhone 12 Pro]
 - OS: [iOS 17.7]
 - React version: [e.g. 18.2.0]
 - React Native version: [e.g. 0.72.6]
 - Node version: [e.g. 22.2.0]
 - yarn version: [1.22.22]
 - @twilio/voice-react-native-sdk [1.2.0]

**Comment by bobiechen-twilio** [comment] 2024-10-09 21:19
Hi @oleksiiSevrukovRedvike 
It looks like you are running into similar issue [here](https://github.com/twilio/twilio-voice-react-native/issues/369): Please check out the suggestions in #369 and see if the issue is resolved after applying the fixes.

**Comment by oleksiiSevrukovRedvike** [comment] 2024-10-15 12:36
hi @bobiechen-twilio thanks for your suggestion, looks like the problem was with `new Voice` initialization, I've added `useMemo` for `new Voice` as it was in example and it works

**Comment by mhuynh5757** [comment] 2024-10-21 17:54
Hi @oleksiiSevrukovRedvike glad to hear that you issue is resolved. I will close this issue for now, please reopen the issue or file another one if you encounter the issue again.

**Closed by mhuynh5757** 2024-10-21 17:54 UTC
