### ISSUE TITLE
The incoming call is not working in Kill mode 

### ISSUE THREAD

**Issue by sushantsi** [twilio/twilio-voice-react-native#115] opened 2022-12-02 17:59 UTC
Hello team hope you are doing well, and thanks for all your help, we got another issue, ie 

Testing in Android,

we are trying to implement incoming calls in all 3 scenario

1 - App in the foreground - we received an incoming call notification and it working properly

2 -App in the background - we received an incoming call notification and it working properly but here application is still in the background mode it should open right? when we click on "Accept"

3 - App in the kill/ close mode - we received an incoming call notification and when we click "Accept" the call is disconnected.

**Comment by kbagchiGWC** [comment] 2022-12-06 16:46
Hi @sushantsi 

Thanks for using the [twilio-voice-react-native](https://github.com/twilio/twilio-voice-react-native) SDK. 

We will be looking at the issue as soon as possible. In the mean time, can you let us know if the issue is device/API level specific? Can you provide steps to reproduce use case 3 and device logs?

**Comment by sushantsi** [comment] 2022-12-07 08:24
Hi @kbagchiGWC 

Thank you for to reach us, but yesterday I resolved this by downgrading the target SDK from 31 to 30. the issue will come when trying to run an app in Android 12 with a target SDK 31. 
with targetSdkVersion = 30 resolved both issues

**Comment by mhuynh5757** [comment] 2022-12-07 19:20
Hi @sushantsi, thanks for the update. I believe we have a ticket to track a fix for this internally. I'm going to close out this issue now. Please let us know if you have further issues. Thanks!

**Closed by mhuynh5757** 2022-12-07 19:20 UTC

**Comment by GuilhermeLessa** [comment] 2023-11-10 14:29
@sushantsi could you send me basics configurations you have done to be able to receive incomings? voice implementations, gradle files, manifest, all this kind of things... I'm completely unshure if I have here is enough, incomings is not beeing notified even if I have all settings as the doc, but twilio doc are always uncompleted...

**Comment by asadumair** [comment] 2024-11-26 13:24
same issue we are facing in ios side like when we receive the call in foreground or background it is working fine but when we receive the call from notification and app is then app will be open but look like freeze no events are fired in twilio-voice-react-native SDK.
