### ISSUE TITLE
Version 1.0.0 - How to use `displayName` with new approach for call push notifications? 

### ISSUE THREAD

**Issue by dev3whistlebiz** [twilio/twilio-voice-react-native#352] opened 2024-04-02 15:29 UTC
# Issue
No clear statement about how to use new approach with call push notifications 
`incoming_call_caller_name_text`, `outgoing_call_caller_name_text` and `answered_call_caller_name_text` instead of `displayName`.

## Pre-submission Checklist
- [X] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
After reading docs, spending some time in [issues section](https://github.com/twilio/twilio-voice-react-native/issues/207#issuecomment-2029140992) and [java code pull request for push notifications](https://github.com/twilio/twilio-voice-react-native/commit/d78d755b184acae82de0b65baacc86dcd893be48#diff-5a3c0b9c5dc7042f7c67fd71b44638f74ed3af6e10ae4b60b97de783766bc9b1) still not sure how to use this new approach for setting caller name instead of number. Since 

> Custom functionality around the displayName TwiML parameter has been removed

then what to use instead of `displayName`?

## Reproduction Steps
It is more question about documentation and example of using new approach with push notifications than a bug.

## Expected Behavior
Documentation providing more information about new way of using push notifications with some examples.

## Actual Behavior
Currently there is very little of information about push notifications (please see [changelog](https://www.twilio.com/docs/voice/sdks/react-native/changelog))

## Reproduction Frequency
Please refer to `Reproduction Steps` section.

## Software and Device Information
Please refer to `Reproduction Steps` section.

## Additional Context
N/A

**Comment by mhuynh5757** [comment] 2024-04-02 20:56
Hi @dev3whistlebiz thanks for bringing this to our attention. Are you targeting both iOS and Android, or just Android? We're always looking to improve our docs. Do you think that a code snippet on how and where to put those string resources would be sufficient?

**Comment by jgozner** [comment] 2024-04-02 21:01
@mhuynh5757 I was also looking for documentation on this for both Android and IOS

**Comment by dev3whistlebiz** [comment] 2024-04-02 21:06
Hello @mhuynh5757 . Thanks for response! I am targeting both iOS and Android. Before the update I was using `client.parameter({name: displayName, value: 'my string value'})` but now it is not working. I tried to put those 3 values that are mentioned in changelog into `strings.xml` file in android directory but still no luck, it shows just a number. I am just confused on how to use it, should I pass those as params in `client.parameter` on back end part or update `strings.xml` file in android directory? In second case how should I pass `'my string value'` then? Thanks in advance for the response! 

P.S. As I mentioned before I am targeting both Android and iOS. Just want to make it work on Android and then look at iOS.

**Comment by mhuynh5757** [comment] 2024-04-04 19:10
Hi all, I'm currently working on improving our documentation. I'll be sure to cover this topic, please stay tuned for it!

**Comment by dev3whistlebiz** [comment] 2024-04-09 14:07
Hello, any updates for this ticket?

**Comment by mhuynh5757** [comment] 2024-04-09 19:35
Hi @dev3whistlebiz the improved documentation has been prioritized and is being worked on. Please stay tuned and thanks for your patience!

**Comment by hieulamblackbird** [comment] 2024-04-10 08:06
hi @mhuynh5757 

in Android , how we can set caller name with `incoming_call_caller_name_text`  for incoming call notifications in string resource on app running ?  As this link   [Change value of R.string programmatically](https://stackoverflow.com/questions/9674925/change-value-of-r-string-programmatically/9679336#9679336)   we cannot edit string resources on Android app running

**Comment by dev3whistlebiz** [comment] 2024-04-11 15:41
Any updates?

**Comment by dev3whistlebiz** [comment] 2024-04-11 19:29
Hello @mhuynh5757 ! Thanks for making PR with update for docs!

After reading [this pull request](https://github.com/twilio/twilio-voice-react-native/pull/357/files) I can't seem to figure out how to set `${from}` or `${to}` params as for example `John, Smith`. Could you please provide more information about that?

**Comment by mhuynh5757** [comment] 2024-04-11 23:08
Hi @dev3whistlebiz thanks for reaching out. The `From` and `To` values are inherent to a call, for example, making a call from a JS client with the identity `alice` to a device using the RN SDK registered as `bob` will see those values being `client:alice` and `client:bob` respectively. You bring up a good point in that there are no other specially considered parameters, is that a use case that you will need?

**Comment by dev3whistlebiz** [comment] 2024-04-12 14:39
Hello @mhuynh5757 ! Thanks for the response! In my case I was using `displayName` that I was making based on phone number. So in my case `From` field was an actual phone number, but server was getting a name by this phone number and passing it to the client side via `displayName`. With new approach I tried but was not able to figure out how should I pass a custom name instead of passing whatever comes in `From` field. Any suggestions on it will be very much appreciated! Thank you!

**Comment by jgozner** [comment] 2024-04-13 07:05
@mhuynh5757 I also have the same requirement. Instead of displaying a phone number I would like to display the person's name that is calling. Was there a reason that `displayName` was removed as a supported parameter? The previous workflow was perfect. 

Additionally, I think adding the following code back to IOS was support setting the caller id to "client:Bob Will" because right now when I try to use that as a caller id the shows up as "client: Bob Will"

  ```
  NSString *handleName = callInvite.from;
  if ([[handleName substringToIndex:7] isEqualToString:@"client:"]) {
      [handleName = handleName stringByReplacingCharactersInRange:NSMakeRange(0, 7) withString:@""];
  }
```

**Comment by periabyte** [comment] 2024-04-15 11:50
Any update on this?

**Comment by mhuynh5757** [comment] 2024-04-16 23:02
Hi all, thanks for the incredible feedback. This kind of feedback is invaluable for us in order to improve the SDK for everyone. I have filed an internal ticket to support this feature, I'll leave the ticket open for now but please rest assured that we're going to discuss this.

**Comment by dev3whistlebiz** [comment] 2024-05-07 18:19
Hello @mhuynh5757!

It has been a while since any updates.. Could you share any new info about this one?

**Comment by periabyte** [comment] 2024-05-09 01:56
@dev3whistlebiz I just used `patch-package` to temporarily support this. I reverted the changes from this PR

https://github.com/twilio/twilio-voice-react-native/pull/339

**Comment by mhuynh5757** [comment] 2024-05-15 21:50
Hi all, thanks for the great community discussion and problem solving. Unfortunately the team has not had a chance to get around to this issue. I understand that using patches is a very unfavorable solution, and I apologize that you have to resort to that for now. Thank you all for your patience!

**Comment by SebassCoates** [comment] 2024-06-17 22:48
Is there a chance that the displayName functionality can be brought back? For us, it was a surefire way to avoid displaying PHI/PII as part of the push notification and to avoid logging that in the iOS call history as well. The provided workarounds are not flexible enough and I'm having a hard time understanding why this feature was removed at all? We're unable to upgrade to the latest release and will be stuck on a beta version.

**Comment by mhuynh5757** [comment] 2024-08-06 19:25
Hi @SebassCoates thanks for checking in. Apologies for the delayed response. We merged a PR that should address your concerns, but we have not made a release that includes this change yet. Please check this PR https://github.com/twilio/twilio-voice-react-native/pull/357

I would like to ask if this suffices for your use case. If not, please let us know where we can improve. Thanks!

**Comment by SebassCoates** [comment] 2024-08-06 20:49
Hi @mhuynh5757 -- I think my concerns are unrelated to documentation updates in your PR. Our use case requires masking PHI for some users but allowing caller ID for others, i.e.
1. The ability to redact the caller ID to avoid passing PHI (phone number) through CallKit
2. The ability for non-HIPAA-constrained users to allow showing the number or a custom display name as Caller ID

This was easily achievable when we could include displayName as a custom parameter (a feature that seems to have been removed). I don't think this is possible on Android with the current release. With iOS, I am nervous that updating the caller ID after the call has been loaded is insufficient for preventing PHI from initially going through CallKit.

Please let me know if I'm mistaken here.

**Comment by hueter** [comment] 2024-08-09 20:22
@mhuynh5757 - just echoing @SebassCoates here:

I'm looking for an Android equivalent to `CallInvite#updateCallerHandle()`. I just want to show the name of the caller using my app's data.

In #357 the docs show how to template data, but `displayName` is no longer available, so it cannot be templated. And there is no `updateCallerHandle` to inject the string of the caller's name for Android.

Is there a way to get around that or should we use the patch package?

**Comment by mhuynh5757** [comment] 2024-08-13 19:47
Hi all, I understand the issue. I will discuss with the team how we can best cover this use case. Thanks for your understanding. I've filed an internal ticket to track this.

**Comment by bojandurmic** [comment] 2024-09-07 09:03
It's a shame that we haven't got an explanation from Twilio devs why this was removed, nor have we got a proper replacement for `displayName`. 

I used `patch-package` as well. This is the content of the patch, if anyone wants to use it. I can confirm it works in latest version of SDK:

```
diff --git a/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/Constants.java b/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/Constants.java
index 8f3844b..e568a6f 100644
--- a/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/Constants.java
+++ b/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/Constants.java
@@ -18,4 +18,5 @@ class Constants {
   public static final String JS_EVENT_KEY_CALL_INFO = "call";
   public static final String JS_EVENT_KEY_CALL_INVITE_INFO = "callInvite";
   public static final String JS_EVENT_KEY_CANCELLED_CALL_INVITE_INFO = "cancelledCallInvite";
+  public static final String DISPLAY_NAME = "displayName";
 }
diff --git a/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java b/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java
index c6b9fa0..4ca57f5 100644
--- a/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java
+++ b/node_modules/@twilio/voice-react-native-sdk/android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java
@@ -1,5 +1,6 @@
 package com.twiliovoicereactnative;
 
+import java.net.URLDecoder;
 import java.security.SecureRandom;
 import java.util.Map;
 import java.util.Objects;
@@ -64,7 +65,13 @@ class NotificationUtility {
     }
     private static String getDisplayName(@NonNull CallInvite callInvite) {
       final String title = callInvite.getFrom();
-      if (title.startsWith("client:")) {
+      Map<String, String> customParameters = callInvite.getCustomParameters();
+      // If "displayName" is passed as a custom parameter in the TwiML application,
+      // it will be used as the caller name.
+      if (customParameters.get(Constants.DISPLAY_NAME) != null) {
+        return URLDecoder.decode(customParameters.get(Constants.DISPLAY_NAME)
+          .replaceAll("\\+", "%20"));
+      } else if (title.startsWith("client:")) {
         return title.replaceFirst("client:", "");
       }
       return title;
diff --git a/node_modules/@twilio/voice-react-native-sdk/ios/TwilioVoiceReactNative+CallKit.m b/node_modules/@twilio/voice-react-native-sdk/ios/TwilioVoiceReactNative+CallKit.m
index 6570384..79509b6 100644
--- a/node_modules/@twilio/voice-react-native-sdk/ios/TwilioVoiceReactNative+CallKit.m
+++ b/node_modules/@twilio/voice-react-native-sdk/ios/TwilioVoiceReactNative+CallKit.m
@@ -12,6 +12,7 @@
 #import "TwilioVoiceReactNativeConstants.h"
 
 NSString * const kDefaultCallKitConfigurationName = @"Twilio Voice React Native";
+NSString * const kCustomParametersKeyDisplayName = @"displayName";
 
 @interface TwilioVoiceReactNative (CallKit) <CXProviderDelegate, TVOCallDelegate, AVAudioPlayerDelegate>
 
@@ -67,7 +68,17 @@ NSString * const kDefaultCallKitConfigurationName = @"Twilio Voice React Native"
 }
 
 - (void)reportNewIncomingCall:(TVOCallInvite *)callInvite {
+    // If "displayName" is passed as a custom parameter in the TwiML application,
+    // it will be used as the caller name.
     NSString *handleName = callInvite.from;
+    NSDictionary *customParams = callInvite.customParameters;
+    
+    if (customParams[kCustomParametersKeyDisplayName]) {
+        NSString *callerDisplayName = customParams[kCustomParametersKeyDisplayName];
+        callerDisplayName = [callerDisplayName stringByReplacingOccurrencesOfString:@"+" withString:@" "];
+        handleName = callerDisplayName;
+    }
+
     if (handleName == nil) {
         handleName = @"Unknown Caller";
     }
```

**Comment by dwbelliston** [comment] 2024-11-17 06:23
It looks like the patch is a potential path forward now, @mhuynh5757 is there any specific reason we may not want to be doing this that you could share? or probably okay?

**Comment by djanowski** [comment] 2024-11-21 18:08
Is there a way to have the SDK format the caller's number in a specific way? I'm looking to format like `(XXX) XXX-XXXX` vs the default E164.

**Comment by mhuynh5757** [comment] 2024-12-11 00:00
Hey all, thanks for the patience on this one. We just released version `1.3.0` that includes a new API that should cover this use case. Please upgrade at your earliest convenience. I am going to close this issue for now, please open new issues if the new API does not cover your use case. Thanks!

**Closed by mhuynh5757** 2024-12-11 00:00 UTC
Labels: enhancement

**Comment by hueter** [comment] 2025-02-22 03:09
@mhuynh5757 

My team has upgraded to 1.4.0 but there's still two problems:

1. The [example interpolation](https://github.com/twilio/twilio-voice-react-native/blob/2b4030db31a1e732e173284f19f792b93e5564fc/src/Voice.tsx#L756) you have of `'Foo ${DisplayName}'` is _literally_ printing "Foo ${DisplayName}" in the caller ID for us, instead of "Foo John Doe" for example. Can you explain a little more or provide documentation for how the variable interpolation is supposed to work?

---

2. We are really in need of an `updateCallerHandle` method for Android, to be able to update the name of the incoming call invite on demand. Since `setIncomingCallContactHandleTemplate` is called on `Voice`, not `Invite`, and it is asynchronous, it doesn't update the incoming call UI "fast enough" to display values on demand while the call is ringing the way that `updateCallerHandle` does on iOS. 

As a result, our iOS customers are getting good caller ID data while Android customers do not. Anything we can try, even if we have to call a native Android API ourselves?

Thank you!

**Comment by dwbelliston** [comment] 2025-02-22 04:13
@hueter - I had success passing the DisplayName from api when dialing the client.

this is roughly what it looks like on the backend, setting up the client dial

```
                tw_action_client = Client(
                    status_callback_event="initiated ringing answered completed",
                    status_callback=status_url,
                    status_callback_method="POST",
                )
                tw_action_client.identity(next_target_team_id_scrubbed)
                tw_action_client.parameter(name="CallId", value=call_id)
                tw_action_client.parameter(
                    name="DisplaName", value=caller_id_for_contact_in
                )
                tw_action_client.parameter(
                    name="ContactId", value=contact_id_for_contact_in
                )
                dial.append(tw_action_client)
```

Not sure if this is an option for you, but this gives the frontend immediate access to the DisplayName

**Comment by hueter** [comment] 2025-02-22 19:59
hey @dwbelliston - thanks for that snippet. We are doing something similar, but display name purely from the backend isn't always enough on the client side.

What does your client code look like? Were you able to get that to show up with `setIncomingCallContactHandleTemplate`, or are you still using the patch package?

**Comment by Pinky-Billava** [comment] 2025-03-16 15:55
Issue: voice.setIncomingCallContactHandleTemplate(${name}); fails to display the contact name on the first incoming call. Instead of the name, it shows the phone number. However, on subsequent incoming calls, the name is displayed correctly.

Any known workarounds or fixes?

**Comment by mhuynh5757** [comment] 2025-03-17 18:43
Hey @Pinky-Billava thanks for reaching out. How are you using that API? It's intended to be used as soon as possible in your application lifecycle. Are you using the method upon CallInvite? Ideally you should invoke it before even registering for incoming calls.
